language: java

jdk:
- oraclejdk8

sudo: false
install: true
dist: trusty

git:
  depth: false
  submodules: false

cache:
  directories:
  - '$HOME/.m2/repository' # cache maven dependencies
  - '$HOME/.sonar/cache' # cache sonar dependencies

branches:
  only:
  - master
  - /^release-.*$/
  # build all branches
  - /.*/

addons:
  # static code analysis dashboard
  sonarcloud:
    # travis ci environment variable with the key of the org (https://sonarcloud.io/account/organizations)
    organization: $SONAR_CLOUD_ORG
    token:
      # travis ci environment variable with the sonar cloud token (https://sonarcloud.io/account/security/)
      secure: $SONAR_CLOUD_KEY

script:
# change to project directory
- cd bogenliga
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=de.bogenliga.application -Dsonar.organization=$SONAR_CLOUD_ORG -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_CLOUD_KEY
- sh /home/travis/build/exxcellent/swt2-bsa-backend/check_sonar_quality_gate.sh $SONAR_CLOUD_PROJECT $TRAVIS_BRANCH

# maven plugin to generate the code coverage report for https://codecov.io
# generate reports for specific projects
#- cd bogenliga-application
#- mvn cobertura:cobertura
#- cd ../bogenliga-business-logic
#- mvn cobertura:cobertura
#- cd ../bogenliga-common
#- mvn cobertura:cobertura

after_success:
# upload reports to https://codecov.io
# uses CODECOV_TOKEN environment variable
#- bash <(curl -s https://codecov.io/bash) -s /home/travis/build/andre-lehnert/mock-backend/bogenliga/bogenliga-application/target/site/cobertura/coverage.xml
#- bash <(curl -s https://codecov.io/bash) -s /home/travis/build/andre-lehnert/mock-backend/bogenliga/bogenliga-business-logic/target/site/cobertura/coverage.xml
#- bash <(curl -s https://codecov.io/bash) -s /home/travis/build/andre-lehnert/mock-backend/bogenliga/bogenliga-common/target/site/cobertura/coverage.xml

